import type { GameEvent } from './types.js';

// ============================================================
// Event Pool — 110 curated events drawn from BrantSteele &
// nguh.org, with tags for relationship-weight logic.
// %0, %1, ... = tribute placeholders (by player index)
// ============================================================

export const EVENT_POOL: GameEvent[] = [
  // ─────────────────────────────────────────────────────────
  // BLOODBATH  (stage: bloodbath) — 30 events
  // ─────────────────────────────────────────────────────────

  {
    id: 'bb-01', stage: 'bloodbath', playerCount: 1,
    message: '%0 sprints away from the Cornucopia.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'retreat'], rarity: 'common',
  },
  {
    id: 'bb-02', stage: 'bloodbath', playerCount: 1,
    message: '%0 grabs a shovel and disappears into the trees.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'weapon'], rarity: 'common',
  },
  {
    id: 'bb-03', stage: 'bloodbath', playerCount: 1,
    message: '%0 grabs a backpack and retreats to the forest.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'retreat'], rarity: 'common',
  },
  {
    id: 'bb-04', stage: 'bloodbath', playerCount: 2,
    message: '%0 and %1 fight for a bag. %0 gives up and retreats.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['combat', 'retreat'], rarity: 'common',
  },
  {
    id: 'bb-05', stage: 'bloodbath', playerCount: 2,
    message: '%0 and %1 fight for a bag. %1 gives up and retreats.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['combat', 'retreat'], rarity: 'common',
  },
  {
    id: 'bb-06', stage: 'bloodbath', playerCount: 1,
    message: '%0 finds a bow, some arrows, and a quiver.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'weapon', 'ranged'], rarity: 'rare',
  },
  {
    id: 'bb-07', stage: 'bloodbath', playerCount: 1,
    message: '%0 dives inside the Cornucopia and hides.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'stealth'], rarity: 'common',
  },
  {
    id: 'bb-08', stage: 'bloodbath', playerCount: 1,
    message: '%0 finds a canteen filled with clean water.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'survival'], rarity: 'common',
  },
  {
    id: 'bb-09', stage: 'bloodbath', playerCount: 1,
    message: '%0 stays at the Cornucopia and claims as many supplies as possible.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'aggressive'], rarity: 'common',
  },
  {
    id: 'bb-10', stage: 'bloodbath', playerCount: 1,
    message: '%0 gathers as much food as possible and vanishes.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'survival'], rarity: 'common',
  },
  {
    id: 'bb-11', stage: 'bloodbath', playerCount: 1,
    message: '%0 grabs a sword from inside the Cornucopia.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'weapon', 'melee'], rarity: 'common',
  },
  {
    id: 'bb-12', stage: 'bloodbath', playerCount: 1,
    message: '%0 takes a spear from inside the Cornucopia.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'weapon', 'melee'], rarity: 'common',
  },
  {
    id: 'bb-13', stage: 'bloodbath', playerCount: 1,
    message: '%0 finds a bag full of explosives.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'weapon', 'explosive'], rarity: 'epic',
  },
  {
    id: 'bb-14', stage: 'bloodbath', playerCount: 1,
    message: '%0 clutches a first aid kit and sprints away.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'healing'], rarity: 'rare',
  },
  {
    id: 'bb-15', stage: 'bloodbath', playerCount: 1,
    message: '%0 takes a sickle from inside the Cornucopia.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'weapon', 'melee'], rarity: 'common',
  },
  {
    id: 'bb-16', stage: 'bloodbath', playerCount: 3,
    message: '%0, %1, and %2 work together to grab as many supplies as possible before fleeing.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: true,
    tags: ['alliance', 'resource'], rarity: 'rare',
  },
  {
    id: 'bb-17', stage: 'bloodbath', playerCount: 1,
    message: '%0 runs off with a lighter and a coil of rope.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'survival'], rarity: 'common',
  },
  {
    id: 'bb-18', stage: 'bloodbath', playerCount: 1,
    message: '%0 snatches a bottle of alcohol and a rag — a makeshift weapon.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'weapon'], rarity: 'common',
  },
  {
    id: 'bb-19', stage: 'bloodbath', playerCount: 1,
    message: '%0 finds a backpack full of camping equipment.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'survival'], rarity: 'common',
  },
  {
    id: 'bb-20', stage: 'bloodbath', playerCount: 1,
    message: '%0 grabs a backpack, not realizing it is completely empty.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'comedic'], rarity: 'common',
  },
  {
    id: 'bb-21', stage: 'bloodbath', playerCount: 2,
    message: '%0 breaks %1\'s nose and steals a basket of bread.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['combat', 'theft'], rarity: 'common',
  },
  {
    id: 'bb-22', stage: 'bloodbath', playerCount: 4,
    message: '%0, %1, %2, and %3 share everything they gathered before scattering.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: true,
    tags: ['alliance', 'resource'], rarity: 'rare',
  },
  {
    id: 'bb-23', stage: 'bloodbath', playerCount: 1,
    message: '%0 retrieves a trident from inside the Cornucopia.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'weapon', 'melee'], rarity: 'rare',
  },
  {
    id: 'bb-24', stage: 'bloodbath', playerCount: 2,
    message: '%0 grabs a jar of fishing bait while %1 claims the fishing gear.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'survival'], rarity: 'common',
  },
  {
    id: 'bb-25', stage: 'bloodbath', playerCount: 2,
    message: '%0 scares %1 away from the Cornucopia.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['intimidation', 'retreat'], rarity: 'common',
  },
  {
    id: 'bb-26', stage: 'bloodbath', playerCount: 1,
    message: '%0 grabs a shield leaning against the Cornucopia.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'weapon', 'defensive'], rarity: 'common',
  },
  {
    id: 'bb-27', stage: 'bloodbath', playerCount: 1,
    message: '%0 snatches a pair of sais from the Cornucopia.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'weapon', 'melee'], rarity: 'rare',
  },
  {
    id: 'bb-28', stage: 'bloodbath', playerCount: 1,
    message: '%0 steps off %G0 podium too soon — the arena erupts in flames.',
    deaths: [0], killers: [], isFatal: true, isAllianceRelated: false,
    tags: ['environment', 'death', 'accident'], rarity: 'epic',
  },
  {
    id: 'bb-29', stage: 'bloodbath', playerCount: 2,
    message: '%0 snaps %1\'s neck before %N1 even reaches the Cornucopia.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'combat', 'instant'], rarity: 'epic',
  },
  {
    id: 'bb-30', stage: 'bloodbath', playerCount: 2,
    message: '%0 finds %1 hiding inside the Cornucopia and kills %A1 with a single blow.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'ambush', 'stealth'], rarity: 'epic',
  },

  // ─────────────────────────────────────────────────────────
  // DAY  (stage: day) — 30 events
  // ─────────────────────────────────────────────────────────

  {
    id: 'd-01', stage: 'day', playerCount: 1,
    message: '%0 goes hunting for other tributes.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'hunting'], rarity: 'common',
  },
  {
    id: 'd-02', stage: 'day', playerCount: 1,
    message: '%0 accidentally injures %R0 while climbing.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'injury'], rarity: 'common',
  },
  {
    id: 'd-03', stage: 'day', playerCount: 1,
    message: '%0 explores the arena cautiously.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'exploration'], rarity: 'common',
  },
  {
    id: 'd-04', stage: 'day', playerCount: 2,
    message: '%0 scares %1 off without a fight.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['intimidation'], rarity: 'common',
  },
  {
    id: 'd-05', stage: 'day', playerCount: 2,
    message: '%0 distracts %1 and escapes into the forest.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'stealth'], rarity: 'common',
  },
  {
    id: 'd-06', stage: 'day', playerCount: 2,
    message: '%0 stalks %1 through the underbrush.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['hunting', 'stealth'], rarity: 'common',
  },
  {
    id: 'd-07', stage: 'day', playerCount: 1,
    message: '%0 fishes in a quiet stream.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'resource'], rarity: 'common',
  },
  {
    id: 'd-08', stage: 'day', playerCount: 1,
    message: '%0 camouflages %R0 in the dense bushes.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'stealth'], rarity: 'common',
  },
  {
    id: 'd-09', stage: 'day', playerCount: 2,
    message: '%0 steals supplies from %1 while %N1 is distracted.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['theft', 'stealth'], rarity: 'common',
  },
  {
    id: 'd-10', stage: 'day', playerCount: 1,
    message: '%0 crafts a wooden spear by the riverbank.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'weapon', 'crafting'], rarity: 'common',
  },
  {
    id: 'd-11', stage: 'day', playerCount: 1,
    message: '%0 discovers a dark cave and marks it as a potential shelter.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'exploration'], rarity: 'common',
  },
  {
    id: 'd-12', stage: 'day', playerCount: 2,
    message: '%0 attacks %1, but %N1 manages to escape.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['combat', 'retreat'], rarity: 'common',
  },
  {
    id: 'd-13', stage: 'day', playerCount: 2,
    message: '%0 chases %1 through the woods.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['hunting', 'chase'], rarity: 'common',
  },
  {
    id: 'd-14', stage: 'day', playerCount: 2,
    message: '%0 runs away from %1 as fast as possible.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'retreat'], rarity: 'common',
  },
  {
    id: 'd-15', stage: 'day', playerCount: 1,
    message: '%0 climbs a tree and picks fresh fruit.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'resource'], rarity: 'common',
  },
  {
    id: 'd-16', stage: 'day', playerCount: 1,
    message: '%0 receives a hatchet from an unknown sponsor.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['sponsor', 'weapon'], rarity: 'rare',
  },
  {
    id: 'd-17', stage: 'day', playerCount: 1,
    message: '%0 receives clean drinking water from an unknown sponsor.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['sponsor', 'survival'], rarity: 'rare',
  },
  {
    id: 'd-18', stage: 'day', playerCount: 1,
    message: '%0 receives medical supplies from an unknown sponsor.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['sponsor', 'healing'], rarity: 'rare',
  },
  {
    id: 'd-19', stage: 'day', playerCount: 1,
    message: '%0 receives fresh food from an unknown sponsor.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['sponsor', 'survival'], rarity: 'rare',
  },
  {
    id: 'd-20', stage: 'day', playerCount: 1,
    message: '%0 searches for a water source.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'resource'], rarity: 'common',
  },
  {
    id: 'd-21', stage: 'day', playerCount: 2,
    message: '%0 defeats %1 in a fight, but spares %G1 life.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: true,
    tags: ['combat', 'mercy', 'alliance'], rarity: 'rare',
  },
  {
    id: 'd-22', stage: 'day', playerCount: 2,
    message: '%0 and %1 work together for the rest of the day.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: true,
    tags: ['alliance', 'cooperation'], rarity: 'common',
  },
  {
    id: 'd-23', stage: 'day', playerCount: 2,
    message: '%0 begs for %1 to kill %A0. %N1 refuses, keeping %0 alive.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: true,
    tags: ['mercy', 'psychological'], rarity: 'rare',
  },
  {
    id: 'd-24', stage: 'day', playerCount: 1,
    message: '%0 tries to sleep through the entire day.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'rest'], rarity: 'common',
  },
  {
    id: 'd-25', stage: 'day', playerCount: 5,
    message: '%0, %1, %2, and %3 raid %4\'s camp while %N4 is out hunting.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['raid', 'theft', 'alliance'], rarity: 'rare',
  },
  {
    id: 'd-26', stage: 'day', playerCount: 1,
    message: '%0 constructs a crude but sturdy shack.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'shelter'], rarity: 'common',
  },
  {
    id: 'd-27', stage: 'day', playerCount: 3,
    message: '%0 overhears %1 and %2 talking in the distance.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'stealth', 'intel'], rarity: 'common',
  },
  {
    id: 'd-28', stage: 'day', playerCount: 1,
    message: '%0 practices %G0 archery skills.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'skill'], rarity: 'common',
  },
  {
    id: 'd-29', stage: 'day', playerCount: 1,
    message: '%0 thinks about home and the people left behind.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['psychological'], rarity: 'common',
  },
  {
    id: 'd-30', stage: 'day', playerCount: 1,
    message: '%0 is pricked by thorns while picking berries.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'injury'], rarity: 'common',
  },
  {
    id: 'd-31', stage: 'day', playerCount: 1,
    message: '%0 searches for firewood.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'resource'], rarity: 'common',
  },
  {
    id: 'd-32', stage: 'day', playerCount: 1,
    message: '%0 travels to higher ground to survey the arena.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'exploration', 'intel'], rarity: 'common',
  },
  {
    id: 'd-33', stage: 'day', playerCount: 1,
    message: '%0 discovers a fast-moving river.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'resource', 'exploration'], rarity: 'common',
  },
  {
    id: 'd-34', stage: 'day', playerCount: 1,
    message: '%0 tends to %1\'s wounds.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: true,
    tags: ['healing', 'alliance', 'cooperation'], rarity: 'rare',
  },
  {
    id: 'd-35', stage: 'day', playerCount: 1,
    message: '%0 sees smoke rising in the distance, but wisely decides not to investigate.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'caution'], rarity: 'common',
  },
  {
    id: 'd-36', stage: 'day', playerCount: 1,
    message: '%0 receives an explosive device from an unknown sponsor.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['sponsor', 'weapon', 'explosive'], rarity: 'epic',
  },
  {
    id: 'd-37', stage: 'day', playerCount: 1,
    message: '%0 questions %G0 sanity as the heat grows unbearable.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['psychological'], rarity: 'common',
  },
  {
    id: 'd-38', stage: 'day', playerCount: 2,
    message: '%0 kills %1 while %N1 rests by a tree.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'ambush', 'stealth'], rarity: 'epic',
  },
  {
    id: 'd-39', stage: 'day', playerCount: 2,
    message: '%0 silently snaps %1\'s neck from behind.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'stealth', 'instant'], rarity: 'epic',
  },
  {
    id: 'd-40', stage: 'day', playerCount: 1,
    message: '%0 bleeds out from untreated wounds sustained earlier.',
    deaths: [0], killers: [], isFatal: true, isAllianceRelated: false,
    tags: ['death', 'infection', 'environment'], rarity: 'rare',
  },
  {
    id: 'd-41', stage: 'day', playerCount: 1,
    message: '%0 unknowingly eats toxic berries.',
    deaths: [0], killers: [], isFatal: true, isAllianceRelated: false,
    tags: ['death', 'accident', 'environment'], rarity: 'rare',
  },
  {
    id: 'd-42', stage: 'day', playerCount: 1,
    message: '%0 dies from an infected cut.',
    deaths: [0], killers: [], isFatal: true, isAllianceRelated: false,
    tags: ['death', 'infection'], rarity: 'rare',
  },
  {
    id: 'd-43', stage: 'day', playerCount: 1,
    message: '%0 dies from hypothermia after a sudden cold snap.',
    deaths: [0], killers: [], isFatal: true, isAllianceRelated: false,
    tags: ['death', 'exposure', 'environment'], rarity: 'rare',
  },
  {
    id: 'd-44', stage: 'day', playerCount: 1,
    message: '%0 dies from hunger.',
    deaths: [0], killers: [], isFatal: true, isAllianceRelated: false,
    tags: ['death', 'hunger'], rarity: 'rare',
  },
  {
    id: 'd-45', stage: 'day', playerCount: 1,
    message: '%0 dies from thirst.',
    deaths: [0], killers: [], isFatal: true, isAllianceRelated: false,
    tags: ['death', 'thirst'], rarity: 'rare',
  },
  {
    id: 'd-46', stage: 'day', playerCount: 2,
    message: '%0 ambushes %1 and drives a spear through %G1 chest.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'ambush', 'combat'], rarity: 'epic',
  },
  {
    id: 'd-47', stage: 'day', playerCount: 6,
    message: '%0, %1, and %2 successfully ambush and kill %3, %4, and %5.',
    deaths: [3, 4, 5], killers: [0, 1, 2], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'ambush', 'combat', 'team'], rarity: 'epic',
  },
  {
    id: 'd-48', stage: 'day', playerCount: 4,
    message: '%0 and %1 track down and kill %2.',
    deaths: [2], killers: [0, 1], isFatal: true, isAllianceRelated: true,
    tags: ['killed', 'hunt', 'alliance'], rarity: 'epic',
  },
  {
    id: 'd-49', stage: 'day', playerCount: 4,
    message: '%0 forces %1 to kill %2 or %3. %N1 chooses to kill %2.',
    deaths: [2], killers: [1], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'coercion', 'psychological'], rarity: 'epic',
  },
  {
    id: 'd-50', stage: 'day', playerCount: 2,
    message: '%0 poisons %1\'s water supply. %N1 drinks it and dies.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'trap', 'poison'], rarity: 'epic',
  },

  // ─────────────────────────────────────────────────────────
  // NIGHT  (stage: night) — 25 events
  // ─────────────────────────────────────────────────────────

  {
    id: 'n-01', stage: 'night', playerCount: 1,
    message: '%0 starts a small fire to stay warm.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'fire'], rarity: 'common',
  },
  {
    id: 'n-02', stage: 'night', playerCount: 1,
    message: '%0 sets up a shelter for the night.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'shelter'], rarity: 'common',
  },
  {
    id: 'n-03', stage: 'night', playerCount: 1,
    message: '%0 loses sight of where %N0 is and panics.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'psychological'], rarity: 'common',
  },
  {
    id: 'n-04', stage: 'night', playerCount: 1,
    message: '%0 climbs a tall tree to rest safely above the ground.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'stealth', 'shelter'], rarity: 'common',
  },
  {
    id: 'n-05', stage: 'night', playerCount: 1,
    message: '%0 goes to sleep, hoping to survive until morning.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'rest'], rarity: 'common',
  },
  {
    id: 'n-06', stage: 'night', playerCount: 2,
    message: '%0 and %1 share stories about home with each other.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: true,
    tags: ['alliance', 'psychological'], rarity: 'common',
  },
  {
    id: 'n-07', stage: 'night', playerCount: 4,
    message: '%0, %1, %2, and %3 take turns keeping watch through the night.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: true,
    tags: ['alliance', 'survival'], rarity: 'common',
  },
  {
    id: 'n-08', stage: 'night', playerCount: 3,
    message: '%0, %1, and %2 take turns keeping watch through the night.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: true,
    tags: ['alliance', 'survival'], rarity: 'common',
  },
  {
    id: 'n-09', stage: 'night', playerCount: 2,
    message: '%0 and %1 take turns keeping watch through the night.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: true,
    tags: ['alliance', 'survival'], rarity: 'common',
  },
  {
    id: 'n-10', stage: 'night', playerCount: 1,
    message: '%0 tends to %G0 wounds by the light of a dying fire.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'healing'], rarity: 'common',
  },
  {
    id: 'n-11', stage: 'night', playerCount: 1,
    message: '%0 spots a distant fire but stays hidden.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'caution'], rarity: 'common',
  },
  {
    id: 'n-12', stage: 'night', playerCount: 1,
    message: '%0 screams for help into the darkness. No one comes.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['psychological'], rarity: 'common',
  },
  {
    id: 'n-13', stage: 'night', playerCount: 1,
    message: '%0 stays awake all night, terrified to close %G0 eyes.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['psychological', 'survival'], rarity: 'common',
  },
  {
    id: 'n-14', stage: 'night', playerCount: 1,
    message: '%0 passes out from exhaustion before reaching shelter.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['survival', 'exposure'], rarity: 'common',
  },
  {
    id: 'n-15', stage: 'night', playerCount: 2,
    message: '%0 and %1 run into each other and agree to a truce for the night.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: true,
    tags: ['alliance', 'truce'], rarity: 'rare',
  },
  {
    id: 'n-16', stage: 'night', playerCount: 4,
    message: '%0 fends %1, %2, and %3 away from %G0 fire.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['combat', 'survival'], rarity: 'rare',
  },
  {
    id: 'n-17', stage: 'night', playerCount: 3,
    message: '%0, %1, and %2 discuss the remaining tributes and their chances.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: true,
    tags: ['alliance', 'psychological'], rarity: 'common',
  },
  {
    id: 'n-18', stage: 'night', playerCount: 2,
    message: '%0 destroys %1\'s supplies while %N1 sleeps.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['sabotage', 'theft'], rarity: 'rare',
  },
  {
    id: 'n-19', stage: 'night', playerCount: 1,
    message: '%0 is awoken by nightmares of the Games.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['psychological'], rarity: 'common',
  },
  {
    id: 'n-20', stage: 'night', playerCount: 2,
    message: '%0 and %1 huddle together for warmth.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: true,
    tags: ['alliance', 'survival'], rarity: 'common',
  },
  {
    id: 'n-21', stage: 'night', playerCount: 1,
    message: '%0 receives a hatchet from an unknown sponsor.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['sponsor', 'weapon'], rarity: 'rare',
  },
  {
    id: 'n-22', stage: 'night', playerCount: 1,
    message: '%0 quietly hums a lullaby to %R0.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['psychological'], rarity: 'common',
  },
  {
    id: 'n-23', stage: 'night', playerCount: 1,
    message: '%0 tends to %1\'s wounds through the night.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: true,
    tags: ['healing', 'alliance'], rarity: 'rare',
  },
  {
    id: 'n-24', stage: 'night', playerCount: 2,
    message: '%0 and %1 hold hands as they drift off to sleep.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: true,
    tags: ['alliance', 'psychological'], rarity: 'common',
  },
  {
    id: 'n-25', stage: 'night', playerCount: 2,
    message: '%0 kills %1 while %N1 sleeps.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'night', 'stealth'], rarity: 'epic',
  },
  {
    id: 'n-26', stage: 'night', playerCount: 2,
    message: '%0 silently snaps %1\'s neck in %G1 sleep.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'night', 'stealth', 'instant'], rarity: 'epic',
  },
  {
    id: 'n-27', stage: 'night', playerCount: 2,
    message: '%0\'s trap kills %1 during the night.',
    deaths: [1], killers: [], isFatal: true, isAllianceRelated: false,
    tags: ['death', 'trap', 'night'], rarity: 'epic',
  },
  {
    id: 'n-28', stage: 'night', playerCount: 1,
    message: '%0 dies from hypothermia in the freezing night air.',
    deaths: [0], killers: [], isFatal: true, isAllianceRelated: false,
    tags: ['death', 'exposure', 'night'], rarity: 'rare',
  },
  {
    id: 'n-29', stage: 'night', playerCount: 3,
    message: '%0 tracks %1 and %2 down under the moonlight and kills them both.',
    deaths: [1, 2], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'night', 'hunt'], rarity: 'epic',
  },
  {
    id: 'n-30', stage: 'night', playerCount: 1,
    message: '%0 accidentally detonates a landmine while trying to set it.',
    deaths: [0], killers: [], isFatal: true, isAllianceRelated: false,
    tags: ['death', 'accident', 'explosive'], rarity: 'epic',
  },

  // ─────────────────────────────────────────────────────────
  // FEAST  (stage: feast) — 15 events
  // ─────────────────────────────────────────────────────────

  {
    id: 'f-01', stage: 'feast', playerCount: 1,
    message: '%0 gathers as much food as possible into a bag before fleeing.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'survival'], rarity: 'common',
  },
  {
    id: 'f-02', stage: 'feast', playerCount: 1,
    message: '%0 sobs while clutching a photo of %G0 friends and family.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['psychological'], rarity: 'common',
  },
  {
    id: 'f-03', stage: 'feast', playerCount: 2,
    message: '%0 and %1 decide to work together to grab more supplies.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: true,
    tags: ['alliance', 'cooperation'], rarity: 'common',
  },
  {
    id: 'f-04', stage: 'feast', playerCount: 2,
    message: '%0 and %1 fight over raw meat. %1 gives up and runs away.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['combat', 'retreat'], rarity: 'common',
  },
  {
    id: 'f-05', stage: 'feast', playerCount: 2,
    message: '%0 and %1 fight over raw meat. %0 gives up and runs away.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['combat', 'retreat'], rarity: 'common',
  },
  {
    id: 'f-06', stage: 'feast', playerCount: 3,
    message: '%0, %1, and %2 confront each other, but grab what they want slowly to avoid conflict.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['caution', 'survival'], rarity: 'common',
  },
  {
    id: 'f-07', stage: 'feast', playerCount: 2,
    message: '%0 destroys %1\'s memoirs out of pure spite.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['psychological', 'sabotage'], rarity: 'rare',
  },
  {
    id: 'f-08', stage: 'feast', playerCount: 4,
    message: '%0, %1, %2, and %3 form a loose alliance to grab weapons, food, and supplies.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: true,
    tags: ['alliance', 'resource'], rarity: 'rare',
  },
  {
    id: 'f-09', stage: 'feast', playerCount: 2,
    message: '%0 steals %1\'s memoirs right out of %G1 hands.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['theft'], rarity: 'common',
  },
  {
    id: 'f-10', stage: 'feast', playerCount: 1,
    message: '%0 takes a sturdy staff leaning against the Cornucopia.',
    deaths: [], killers: [], isFatal: false, isAllianceRelated: false,
    tags: ['resource', 'weapon', 'melee'], rarity: 'common',
  },
  {
    id: 'f-11', stage: 'feast', playerCount: 2,
    message: '%0 snaps %1\'s neck at the Feast.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'feast', 'instant'], rarity: 'epic',
  },
  {
    id: 'f-12', stage: 'feast', playerCount: 2,
    message: '%0 ambushes %1 at the Feast and kills %A1.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'feast', 'ambush'], rarity: 'epic',
  },
  {
    id: 'f-13', stage: 'feast', playerCount: 4,
    message: '%0, %1, and %2 successfully ambush and kill %3 at the Feast.',
    deaths: [3], killers: [0, 1, 2], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'feast', 'ambush', 'team'], rarity: 'epic',
  },
  {
    id: 'f-14', stage: 'feast', playerCount: 5,
    message: '%0, %1, %2, and %3 hunt down and kill %4 at the Feast.',
    deaths: [4], killers: [0, 1, 2, 3], isFatal: true, isAllianceRelated: true,
    tags: ['killed', 'feast', 'hunt', 'team', 'alliance'], rarity: 'epic',
  },
  {
    id: 'f-15', stage: 'feast', playerCount: 1,
    message: '%0 bleeds out from old wounds at the Feast.',
    deaths: [0], killers: [], isFatal: true, isAllianceRelated: false,
    tags: ['death', 'infection', 'feast'], rarity: 'rare',
  },

  // ─────────────────────────────────────────────────────────
  // ALL-STAGE  (stage: all) — 20 events — valid any time
  // ─────────────────────────────────────────────────────────

  {
    id: 'a-01', stage: 'all', playerCount: 2,
    message: '%0 throws a knife into %1\'s head.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'ranged', 'instant'], rarity: 'epic',
  },
  {
    id: 'a-02', stage: 'all', playerCount: 1,
    message: '%0 accidentally steps on a landmine.',
    deaths: [0], killers: [], isFatal: true, isAllianceRelated: false,
    tags: ['death', 'trap', 'accident'], rarity: 'epic',
  },
  {
    id: 'a-03', stage: 'all', playerCount: 2,
    message: '%0 catches %1 off guard and kills %A1 with a single strike.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'ambush', 'stealth'], rarity: 'epic',
  },
  {
    id: 'a-04', stage: 'all', playerCount: 3,
    message: '%0 and %1 work together to drown %2.',
    deaths: [2], killers: [0, 1], isFatal: true, isAllianceRelated: true,
    tags: ['killed', 'alliance', 'combat'], rarity: 'epic',
  },
  {
    id: 'a-05', stage: 'all', playerCount: 2,
    message: '%0 strangles %1 after an intense fist fight.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'combat', 'melee'], rarity: 'epic',
  },
  {
    id: 'a-06', stage: 'all', playerCount: 2,
    message: '%0 shoots an arrow into %1\'s head.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'ranged', 'instant'], rarity: 'epic',
  },
  {
    id: 'a-07', stage: 'all', playerCount: 1,
    message: '%0 cannot handle the pressure and commits suicide.',
    deaths: [0], killers: [], isFatal: true, isAllianceRelated: false,
    tags: ['death', 'self', 'psychological'], rarity: 'rare',
  },
  {
    id: 'a-08', stage: 'all', playerCount: 2,
    message: '%0 bashes %1\'s head against a rock multiple times.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'combat', 'melee'], rarity: 'epic',
  },
  {
    id: 'a-09', stage: 'all', playerCount: 2,
    message: '%0 decapitates %1 with a sword.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'weapon', 'melee'], rarity: 'epic',
  },
  {
    id: 'a-10', stage: 'all', playerCount: 2,
    message: '%0 spears %1 through the abdomen.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'weapon', 'melee'], rarity: 'epic',
  },
  {
    id: 'a-11', stage: 'all', playerCount: 2,
    message: '%0 sets %1 on fire with a Molotov cocktail.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'weapon', 'fire'], rarity: 'epic',
  },
  {
    id: 'a-12', stage: 'all', playerCount: 2,
    message: '%0 stabs %1 while %G1 back is turned.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'stealth', 'melee'], rarity: 'epic',
  },
  {
    id: 'a-13', stage: 'all', playerCount: 2,
    message: '%0 severely injures %1, but mercifully puts %A1 out of %G1 misery.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'mercy', 'combat'], rarity: 'epic',
  },
  {
    id: 'a-14', stage: 'all', playerCount: 2,
    message: '%0 severely injures %1 and leaves %A1 to die slowly.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'cruelty', 'combat'], rarity: 'epic',
  },
  {
    id: 'a-15', stage: 'all', playerCount: 2,
    message: '%0 bashes %1\'s head in with a mace.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'weapon', 'melee'], rarity: 'epic',
  },
  {
    id: 'a-16', stage: 'all', playerCount: 2,
    message: '%0 pushes %1 off a cliff during a knife fight.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'environment', 'combat'], rarity: 'epic',
  },
  {
    id: 'a-17', stage: 'all', playerCount: 2,
    message: '%0 throws a knife into %1\'s chest.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'ranged', 'weapon'], rarity: 'epic',
  },
  {
    id: 'a-18', stage: 'all', playerCount: 2,
    message: '%0 convinces %1 not to kill %A0, then turns around and kills %A1 instead.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: true,
    tags: ['killed', 'betrayal', 'psychological'], rarity: 'epic',
  },
  {
    id: 'a-19', stage: 'all', playerCount: 3,
    message: '%0, %1, and %2 get into a fight. %0 emerges victorious, killing them both.',
    deaths: [1, 2], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'combat', 'survivor'], rarity: 'epic',
  },
  {
    id: 'a-20', stage: 'all', playerCount: 2,
    message: '%0 kills %1 with %G1 own weapon.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'combat', 'irony'], rarity: 'epic',
  },
  {
    id: 'a-21', stage: 'all', playerCount: 2,
    message: '%0 overpowers %1 and kills %A1.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'combat', 'melee'], rarity: 'epic',
  },
  {
    id: 'a-22', stage: 'all', playerCount: 2,
    message: '%0 detonates an explosive, killing %1.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'explosive'], rarity: 'epic',
  },
  {
    id: 'a-23', stage: 'all', playerCount: 4,
    message: '%0 detonates an explosive, killing %1, %2, and %3.',
    deaths: [1, 2, 3], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'explosive', 'mass'], rarity: 'epic',
  },
  {
    id: 'a-24', stage: 'all', playerCount: 2,
    message: '%0 kills %1 with a hatchet.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'weapon', 'melee'], rarity: 'epic',
  },
  {
    id: 'a-25', stage: 'all', playerCount: 4,
    message: '%0 and %1 fight %2 and %3. %0 and %1 survive the encounter.',
    deaths: [2, 3], killers: [0, 1], isFatal: true, isAllianceRelated: true,
    tags: ['killed', 'combat', 'alliance', 'team'], rarity: 'epic',
  },
  {
    id: 'a-26', stage: 'all', playerCount: 3,
    message: '%0 attacks %1, but %2 protects %A1, killing %0 instead.',
    deaths: [0], killers: [2], isFatal: true, isAllianceRelated: true,
    tags: ['killed', 'defense', 'alliance'], rarity: 'epic',
  },
  {
    id: 'a-27', stage: 'all', playerCount: 2,
    message: '%0 kills %1 with a sickle.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'weapon', 'melee'], rarity: 'epic',
  },
  {
    id: 'a-28', stage: 'all', playerCount: 2,
    message: '%0 strangles %1 with a rope.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'weapon', 'melee'], rarity: 'epic',
  },
  {
    id: 'a-29', stage: 'all', playerCount: 2,
    message: '%0 kills %1 for %G1 supplies.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'theft', 'survival'], rarity: 'epic',
  },
  {
    id: 'a-30', stage: 'all', playerCount: 3,
    message: '%0 shoots an arrow at %1 but misses and kills %2 instead.',
    deaths: [2], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'accident', 'ranged'], rarity: 'epic',
  },
  {
    id: 'a-31', stage: 'all', playerCount: 2,
    message: '%0 shoots a poisonous blow dart into %1\'s neck. %1 dies slowly.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'poison', 'ranged'], rarity: 'epic',
  },
  {
    id: 'a-32', stage: 'all', playerCount: 2,
    message: '%0 stabs %1 with a sharp tree branch.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'environment', 'melee'], rarity: 'epic',
  },
  {
    id: 'a-33', stage: 'all', playerCount: 1,
    message: '%0 falls into a pit and dies.',
    deaths: [0], killers: [], isFatal: true, isAllianceRelated: false,
    tags: ['death', 'accident', 'environment'], rarity: 'rare',
  },
  {
    id: 'a-34', stage: 'all', playerCount: 1,
    message: '%0 falls into a frozen lake and drowns.',
    deaths: [0], killers: [], isFatal: true, isAllianceRelated: false,
    tags: ['death', 'environment', 'exposure'], rarity: 'rare',
  },
  {
    id: 'a-35', stage: 'all', playerCount: 2,
    message: '%0 and %1 threaten a double suicide. Both die.',
    deaths: [0, 1], killers: [], isFatal: true, isAllianceRelated: true,
    tags: ['death', 'self', 'psychological', 'alliance'], rarity: 'epic',
  },
  {
    id: 'a-36', stage: 'all', playerCount: 1,
    message: '%0 betrays %1 — %0 was a false ally all along.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: true,
    tags: ['killed', 'betrayal', 'alliance'], rarity: 'epic',
  },
  {
    id: 'a-37', stage: 'all', playerCount: 2,
    message: '%0\'s trap kills %1.',
    deaths: [1], killers: [], isFatal: true, isAllianceRelated: false,
    tags: ['death', 'trap'], rarity: 'rare',
  },
  {
    id: 'a-38', stage: 'all', playerCount: 2,
    message: '%0 shoots a spear through %1\'s heart.',
    deaths: [1], killers: [0], isFatal: true, isAllianceRelated: false,
    tags: ['killed', 'weapon', 'ranged'], rarity: 'epic',
  },
  {
    id: 'a-39', stage: 'all', playerCount: 1,
    message: '%0 dies trying to escape the arena.',
    deaths: [0], killers: [], isFatal: true, isAllianceRelated: false,
    tags: ['death', 'accident', 'environment'], rarity: 'rare',
  },
  {
    id: 'a-40', stage: 'all', playerCount: 1,
    message: '%0 dies of dysentery.',
    deaths: [0], killers: [], isFatal: true, isAllianceRelated: false,
    tags: ['death', 'illness', 'environment'], rarity: 'rare',
  },
];

export const EVENT_POOL_STATS = {
  total: EVENT_POOL.length,
  byStage: {
    bloodbath: EVENT_POOL.filter(e => e.stage === 'bloodbath').length,
    day:       EVENT_POOL.filter(e => e.stage === 'day').length,
    night:     EVENT_POOL.filter(e => e.stage === 'night').length,
    feast:     EVENT_POOL.filter(e => e.stage === 'feast').length,
    all:       EVENT_POOL.filter(e => e.stage === 'all').length,
  },
  byRarity: {
    common: EVENT_POOL.filter(e => e.rarity === 'common').length,
    rare:   EVENT_POOL.filter(e => e.rarity === 'rare').length,
    epic:   EVENT_POOL.filter(e => e.rarity === 'epic').length,
  },
  fatal:     EVENT_POOL.filter(e => e.isFatal).length,
  nonFatal:  EVENT_POOL.filter(e => !e.isFatal).length,
};
